// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUj7sg2mbATyI4FVxu7XXJNMYSi2ViYXk',
    appId: '1:542833402995:web:a0df2dfd5856dab814f606',
    messagingSenderId: '542833402995',
    projectId: 'flutter-firebase-6e6fa',
    authDomain: 'flutter-firebase-6e6fa.firebaseapp.com',
    storageBucket: 'flutter-firebase-6e6fa.appspot.com',
    measurementId: 'G-FL9MEEKL50',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiQORZXRyYDLG4AJ7jg_veKDsPqKXt3Ck',
    appId: '1:542833402995:android:b4c9919de373ee1414f606',
    messagingSenderId: '542833402995',
    projectId: 'flutter-firebase-6e6fa',
    storageBucket: 'flutter-firebase-6e6fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhDovnL1AHaPWCvUaehtZY42OVSown5Nw',
    appId: '1:542833402995:ios:75e73ef364e8e76d14f606',
    messagingSenderId: '542833402995',
    projectId: 'flutter-firebase-6e6fa',
    storageBucket: 'flutter-firebase-6e6fa.appspot.com',
    iosClientId: '542833402995-tlobghbrm0tulnee2rqo108ao183bs0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPracticeIntroduction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhDovnL1AHaPWCvUaehtZY42OVSown5Nw',
    appId: '1:542833402995:ios:75e73ef364e8e76d14f606',
    messagingSenderId: '542833402995',
    projectId: 'flutter-firebase-6e6fa',
    storageBucket: 'flutter-firebase-6e6fa.appspot.com',
    iosClientId: '542833402995-tlobghbrm0tulnee2rqo108ao183bs0q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPracticeIntroduction',
  );
}
